---
# defaults file for roles/elasticsearch_supervisor_logstash

# setup supervisor
BASE_USER: tourk
BASE_GROUP: tourk
BASE_PATH: /software
SUPERVISOR_CONF_PATH: "{{ BASE_PATH }}/supervisor/conf"
SUPERVISOR_LOGS_PATH: "{{ BASE_PATH }}/supervisor/logs"
SUPERVISOR_CONF_NAME: supervisord.conf
# setup supervisord end

# logstash setup
LOSGTASH_USER: logstash
LOGSTASH_HOME_PATH: /software/logstash-5.2.2
LOGSTASH_DATA_PATH: /software/data/logstash/data
LOGSTASH_LOGS_PATH: /software/data/logstash/logs
LOGSTASH_CONF_NAME: logstash_agent.conf
LOSGTASH_START_CONFIG_PATH: /software/logstash-5.2.2/config
LOGSTASH_Xms: 2g
LOGSTASH_Xmx: 2g