---
# install x-pack for elasticsearch0cluster

# 传送插件
- name: transfer x-pack to remote server
  copy:
    src: x-pack-5.2.2.zip
    dest: "{{ top_dir }}x-pack-5.2.2.zip"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0644



# 只启用监控功能--因为监控功能免费
# 传送申请的 license 文件到远程
# 需要收到运行 curl -XPUT -u elastic 'http://172.31.10.119:9200/_xpack/license?acknowledge=true' -d @/software/data/elastic5/license.json password: changeme
- name: transfer license.json to remote server
  copy:
    src: license.json
    dest: "{{ top_dir }}license.json"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0644