---
- name: restart mysql for centos6
  service: 
    name: mysqld
    state: restarted
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == "6"

- name: restart mysql centos7
  systemd:
    state: restarted
    daemon_reload: yes
    name: mysql
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == "7"