---
# tasks file for roles/elasticsearch_kibana

# 创建 kibans 使用的用户
- name: Create User  {{ user }} For  elasticsearch-cluster
  user: name={{ user }}
        state=present
        password={{ user_password }}
        comment="user for elasticsearch-cluster"
        append=yes

# 安装 jdk
# - name: Install Java 8u51 for kibana
#   unarchive:
#     src: jdk-8u51-linux-x64.tar.gz
#     dest: "{{BASE_HOME}}"


# 安装 kibana
- name: Insatll kibana for elasticsearch_cluster
  unarchive:
    src: kibana-5.2.2-linux-x86_64.tar.gz
    dest: "{{BASE_HOME}}"
    owner: "{{ user }}"
    group: "{{ user }}"

# 传送配置文件
- name: transfer config to kibana
  template:
    src: kibana.yml.j2
    dest: "{{ BASE_HOME }}/{{ KIBANA_NAME }}/config/kibana.yml"
    owner: "{{ user }}"
    group: "{{ user }}"

# 传送脚本到远程 需要收到到服务器启动
- name: transfer init script to kibana
  template:
    src: kibana_handle.sh.j2
    dest: "{{ BASE_HOME }}/kibana_handle.sh"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0755

# 安装 x-pack 插件
- name: include plugins.yml
  include: plugins.yml