---
#Setup Supervisor 
- name: Jange Packages save_path === 判断存放 tar 包的路径是否存在
  file: dest={{remote_packages_save_path}} mode=0755 state=directory
  tags: install supervisord


- name: Jange supervisord directory isn't exits Create === 判断存放 supervisord 的配置文件信息的目录是否存在
  file: dest={{item}} mode=0755 state=directory
  with_items: setup_supervisord
  tags: install supervisord


- name: extracted Fiels To Remote directory supervisor files === 直接解压安装文件到远程 tar 包存放路径
  unarchive: src={{item}} dest={{remote_packages_save_path}}
  with_items: supervisor
  tags: install supervisord


- name: Install supervisor === 开始安装 supervisor
  shell: python setup.py install
  args:
    chdir: "{{remote_packages_save_path}}{{item}}"
  with_items: supervisor_directory
  tags: install supervisord


# if python is 2.7.10 add
# - name: Setup supervisord conf === 初始化 supervisord 配置文件
#   shell: /usr/local/bin/echo_supervisord_conf > /etc/supervisord.conf
#   args:
#     chdir: /usr/local/bin/
#   tags: install supervisord


- name: Setup supervisord conf === 初始化 supervisord 配置文件
  shell: echo_supervisord_conf > /etc/supervisord.conf
  tags: install supervisord

- name: Add mappings to /etc/supervisord.conf === 添加 supervisor 配置文件内容,supervisor 启动读取外部配置文件
  blockinfile:
    dest: /etc/supervisord.conf
    block: |
      {{item.info}}
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{item.name}}"
  with_items: supervisor_conf
  tags: install supervisord
#supervisor starup conf
- name: Config Logstash conf === 配置 supervisor 启动读取的配置文件.
  template: src=logstash-supervisor.conf.j2 dest="{{supervisor_conf_path}}{{supervisor_conf_name}}"
  tags: install supervisord
#Setup Supervisor end


#setup Logstash
- name: extracted Fiels To Remote directory Logstash files === 安装 logstash->直接解压安装文件到远程
  unarchive: src={{logstash_source_file_name}} dest={{remote_packages_save_path}}
  tags: install logstash


- name: move Logstash To Logstash home === 配置 logstash 的 home目录
  shell: mv -f {{logstash_unzip_last}} {{logstash_home}}
  tags: install logstash


- name: create start Logstash user === 创建 Logstash启动用户
  user: name={{logstash_user}} shell=/sbin/nologin
  tags: install logstash


- name: Copy Logstash conf to Remote === 传输抓取日志的 logstash 配置文件
  template: src=logstash-shipper.conf.j2 dest="{{logstash_conf_path}}{{logstash_conf_name}}"
  tags: install logstash
  notify:
    - restart supervisor
#setup logstash end


#copy script to remote
- name: supervisord script === 配置 supervisord 到系统中
  template: src=supervisor.sh.j2 dest=/etc/init.d/supervisor mode=0755
  
