---
# 基础公用检测目录
- name: Check that the directory exists
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ supervisor_home }}"
    - "{{ supervisor_program }}"
    - "{{ supervisor_log }}"
    - "{{ packages_path }}"

- name: Install supervisor form Local
  include: perform_local/main.yml

- name: Transfer configuration files for the supervisor
  template:
    src: supervisor.conf.j2
    dest: "{{ supervisor_home }}/supervisord.conf"

- name: Transfer script files for the supervisor
  template:
    src: supervisord.sh.j2
    dest: "{{ supervisor_home }}/supervisord.sh"
    mode: 0755