---
# handlers file for nginx
- name: enable service nginx
  service: name=nginx enabled=yes
- name: start nginx
  service: name=nginx state=started 
- name: restart crond
  service: name=crond state=restarted
- name: restart nginx
  service: name=nginx state=restarted