---
- name: Create Nginx Packeges Temp Dir
  file:
    dest={{ soft_dir }} 
    mode=755
    state=directory
- name: NGINX {{ ansible_eth0.ipv4.address }} | Installing NGINX source | Copy software packages to Client
  copy:
    src={{ item }} dest={{ soft_dir }} mode=0755
  with_items:
    - "files/pcre-8.39.tar.gz"
    - "files/zlib-1.2.8.tar.gz"
    - "files/openssl-1.0.2f.tar.gz"
    - "files/nginx-1.8.0.tar.gz"
# - name: NGINX {{ ansible_eth0.ipv4.address }} | Starting Install NGINX
#   shell:
#     /bin/bash {{ soft_dir }}nginx_install.sh
- name: Run Local Script At Remote Server
  script: files/nginx_install.sh
- name: Remove Temp Packages Dir
  file:
    dest={{ soft_dir }}
    state=absent
- name: Template NGINX CONFIG To Clients
  template:
    src=templates/nginx.conf.j2
    dest={{ nginx_dir }}conf/nginx.conf
    mode=0644
- name: Copy System Nginx Script To /etc/init.d/
  copy:
    src="files/nginx.sh" dest="/etc/init.d/nginx" mode=0755
- name: Add Nginx Script System
  command: /sbin/chkconfig nginx on
  become: yes
  become_method: sudo
- name: Staring Nginx Service of system Script
  service: name=nginx state=started
- name: NGINX {{ ansible_eth0.ipv4.address }} | Copy Index.html To Clients Test Nginx Starting 
  template:
    src=templates/index.html.j2
    dest={{ nginx_dir }}html/index.html
    owner=nginx
    group=nginx
    mode=0755