---
- name: create mysql group
  group:
    name: "{{ GROUP }}"
    gid: 1100
    state: present

- name: create mysql user
  user:
    name: "{{ USER }}"
    comment: "Mysql user"
    shell: /usr/sbin/nologin
    uid: 1100
    group: "{{ GROUP }}"

- name: Installation dependencies
  yum:
    name: "{{ item }}"
    state: latest
  with_items: "{{ packages }}"