---
# mysql 安装依赖
#- name: mysql libaio install
#  copy:
#    src: ../../source_files/mysql/libaio-0.3.109-13.el7.x86_64.rpm
#    dest: /tmp/
#
#- name: install libaio
#  shell: rpm -ivh libaio-0.3.109-13.el7.x86_64.rpm
#  args:
#    chdir: /tmp
# mysql rpm 方式安装
- name: mysql rpm packages
  unarchive:
    src: ../../source_files/mysql/el7.tar.gz
    dest: /tmp/

- name: The install mysql rpm for centos 7
  shell: "rpm -ivh MySQL-*"
  args:
    chdir: /tmp