---
# mysql rpm 方式安装
- name: mysql rpm packages
  unarchive:
    src: /Users/yuloong/Desktop/OneDrive - inc/packages/mysql/el6.tar.gz
    dest: /tmp/

- name: The install mysql rpm for centos 6
  shell: "rpm -ivh MySQL-*"
  args:
    chdir: /tmp