---
- name: Installation Preparation
  include: Installation_Preparation/main.yml

- name: Installation
  include: Installation/main.yml

- name: configuration nginx
  include: configuration/main.yml

- name: management_cron
  include: management_cron/main.yml
