---
# tasks file for catalina_out
TOMCAT_HOME: "/software/tomcat_{{ project_name }}"
TOMCAT_LIB_HOME: "{{ TOMCAT_HOME }}/lib"
TOMCAT_BIN_HOME: "{{ TOMCAT_HOME }}/bin"
TOMCAT_LOGS_HOME: "{{ TOMCAT_HOME }}/logs"
TOMCAT_CONF_HOME: "{{ TOMCAT_HOME }}/conf"
SCRIPT_DIRECTORY: "/software/script"