---
# This is update epel for centos 7 or 6

# 安装EPEL 源
- name: install epel repo local for centos 6
  copy:
    src: ../../../source_files/epel-release-latest-6.noarch.rpm
    dest: /tmp/epel-release-latest-6.noarch.rpm
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == "6"


- name: install epel repo local for centos 7
  copy:
    src: ../../../source_files/epel-release-latest-7.noarch.rpm
    dest: /tmp/epel-release-latest-7.noarch.rpm
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == "7"


- name: install local epel repo
  shell: "rpm -ivh /tmp/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
  register: result_stdout


- debug:
    msg: "System epel repo has installed"
  when: result_stdout.rc == 0
