---
# This is for install solrcloud
# 传送已经配置好的 solrcloud 配置文件和目录结构
- name: unarchive solrcloud files to remote server
  unarchive:
    src: "../../../source_files/solrcloud4.10/solrcloud_home.tar.gz"
    dest: "{{ BASE_HOME }}"
    owner: "{{ TOMCAT_USER }}"
    group: "{{ TOMCAT_GROUP }}"


# 传送配置好的 tomcat 
- name: unarchive tomcat files to remote server
  unarchive:
    src: "../../../source_files/solrcloud4.10/solrcloud_tomcat.tar.gz"
    dest: "{{ BASE_HOME }}"
    owner: "{{ TOMCAT_USER }}"
    group: "{{ TOMCAT_GROUP }}"
  notify: restart tomcat

# 配置 tomcat 脚本
# install tomcat script
- name: transfer script for tomcat7
  template:
    src: tomcat_init.sh.j2
    dest: /etc/init.d/tomcat
    mode: 0755

# Add Tomcat Into local
- name: Start Tomcat
  service: name=tomcat state=started enabled=yes