---
- name: 安装 依赖包
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - make
    - gcc
    - gcc-c++
    - openssl
    - openssl-devel
    - libnl
    - libnl-devel
    - libnfnetlink-devel
    - psmisc