---
- name: download psutil
  unarchive:
    src: "../../../source_files/psutil-5.4.3.tar.gz"
    dest: /tmp/

- name: install setuptools
  shell: "python setup.py install"
  args:
    chdir: /tmp/psutil-5.4.3
  become: yes
  become_method: sudo
  become_user: root