---
- name: 删除默认安装的防火墙
  yum: 
    name: "{{ item }}"
    state: absent
  with_items:
    - firewalld
    - python-firewall
    - firewalld-filesystem

- name: 添加EPEL仓库
  yum: 
    name: epel-release
    state: latest

- name: 安装基础软件包
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - psmisc        # 安装psmisc 才能使用命令killall，它在keepalive的监测脚本中使用到
    - nfs-utils     # 挂载nfs 共享文件需要 (创建基于 nfs的PV 需要)
    - jq                  # 轻量JSON处理程序，安装docker查询镜像需要
    - socat               # 用于port forwarding
    - bash-completion     # bash命令补全工具，需要重新登录服务器生效
    - rsync               # 文件同步工具，分发证书等配置文件需要
    - ipset
    - ipvsadm

- name: 永久关闭 selinux
  lineinfile:
    dest: /etc/selinux/config
    regexp: "^SELINUX="
    line: "SELINUX=disabled"

- name: 设置 ulimits
  template: 
    src: ulimits.conf.j2
    dest: /etc/security/limits.d/ulimits.conf

- name: 禁用系统 swap
  shell: "swapoff -a && sysctl -w vm.swappiness=0"
  ignore_errors: true

- name: 删除fstab swap 相关配置
  lineinfile:
    path: /etc/fstab
    regexp: 'swap'
    state: absent
    backup: 'yes'

- name: 加载内核模块
  modprobe:
    name: "{{ item }}"
    state: present
  with_items:
    - br_netfilter  # 简单说明就是数据包的转发机制 一下模块好像都跟 iptables有关
    - ip_vs_rr 
    - ip_vs_rr
    - ip_vs_wrr
    - ip_vs_sh
    - nf_conntrack_ipv4
  ignore_errors: true

- name: 设置系统参数
  template:
    src: k8s.conf.j2
    dest: /etc/sysctl.d/k8s.conf

- name: 生效系统参数
  shell: "sysctl -p /etc/sysctl.d/k8s.conf"
  ignore_errors: true
  
- import_tasks: ntpsync.yml