---
# tasks file for mysql
# include mysql_initialization
- name: include mysql_initialization
  include: mysql_initialization/main.yml


- name: include mysql install
  include: mysql_install/main.yml


# 启动 mysql
- name: Transfer Mysql Config To remove Server
  template:
    src=my.cnf.j2
    dest={{mysql_config}}
    mode=0755
  notify:
    - restart mysqld
  tags: change config
  
