---
# 默认安装
- name: unarchive zabbix_agent2.4.4
  unarchive:
    src: zabbix-2.4.4.tar.gz
    dest: /tmp/

- name: zabbix_agent install zabbix_agent2.4.4
  shell: "{{zabbix_configure}} && make && make install"
  args:
    chdir: /tmp/zabbix-2.4.4