---
# 默认安装
- name: clear yum 
  shell: yum clean all


- name: install cofnigure base packages
  # yum: name=gcc state=present
  shell: yum -y install gcc
  become: yes
  become_method: sudo
  become_user: root

- name: unarchive zabbix_agent2.4.4
  unarchive:
    src: "../../../source_files/zabbix-2.4.4.tar.gz"
    dest: /tmp/

- name: zabbix_agent install zabbix_agent2.4.4
  shell: "{{zabbix_configure}} && make && make install"
  args:
    chdir: /tmp/zabbix-2.4.4
  become: yes
  become_method: sudo
  become_user: root

- name: change_agent dir permissions
  file:
    path: "{{ zabbix_agent_home }}"
    mode: 0755
  become: yes
  become_method: sudo
  become_user: root