---
#Script Directory
script_home: /software/script/
#Tomcat Script Vars===程序目录
container_name: "tomcat_{{env}}"
container_home: "/software/{{container_name}}/"
container_java_home: /software/jdk1.7/
container_jre_home: "{{container_java_home}}jre"
#Tomcat Script Vars end
# vars file for deploy==程序名称
deploy_file_name: cybershop-{{env}}-0.0.1-SNAPSHOT.war
deploy_directory: cybershop-{{env}}-0.0.1-SNAPSHOT
##############远程服务器############
#get  setup server time and  create tmp deploy directory ===临时文件存放位置,解压位置
tmp_save_directory: /software/tmp_deploy_directory/
extracted_directory : "{{tmp_save_directory}}{{deploy_directory}}-{{svn_version}}"
#Links Directory===静态资源,图片目录
static_directory: /data/www
picture_directory: /software/upload
#Create Soft To extracted directory===挂载目录
static_link_directory: "{{extracted_directory}}/www"
picture_link_directory: "{{extracted_directory}}/assets/upload"
#Project Directory==程序存放目录
deploy_project_directory_front: /software/deploy-front/
deploy_project_directory_backend: /software/deploy-backend/
deploy_project_directory_mobile: /software/deploy-mobile/
deploy_project_directory_api: /software/deploy-api/
#Create start Tomcat deploy project===程序软连接目录
deploy_link_project_front: "{{deploy_project_directory_front}}{{deploy_directory}}"
deploy_link_project_backend: "{{deploy_project_directory_backend}}{{deploy_directory}}"
deploy_link_project_mobile: "{{deploy_project_directory_mobile}}{{deploy_directory}}"
deploy_link_project_api: "{{deploy_project_directory_api}}{{deploy_directory}}"