---
# 配置 epel 安装 libselinux-python
- name: include update module
  include: update_epel/main.yml


- name: include system_setup
  include: system_setup/main.yml


- name: include install_pip
  include: install_pip/main.yml


# - name: restart machine
#   shell: sleep 2 && shutdown -r now "Ansible updates triggered"
#   async: 1
#   poll: 0
#   # sudo: true
#   ignore_errors: true


# - name: shutdown
#   shell: sleep 2 && shutdown -h now "Ansible updates triggered"
#   async: 1
#   poll: 0
#   # sudo: true
#   ignore_errors: true