---
# 判断是否有外网
- name: Check network connection
  shell: ping -c 4 -i 0.1 www.baidu.com
  register: results_code

- debug:
    msg: "System {{ inventory_hostname }} has Connection internet!!!"
  when: results_code.rc == 0

# 配置 epel 安装 libselinux-python
- name: include update module
  include: update_epel/main.yml


- name: include system_setup
  include: system_setup/main.yml


- name: include install_pip
  include: install_pip/main.yml
  when: results_code.rc == 0