---
# 判断是否有外网
- name: checkne internet connection
  checknetwork: url={{ check_url }}
  register: result

- debug:
    msg: "System {{ inventory_hostname }} has Connection internet!!!"
  when: result.stdotut == 'Connection'

# 配置 epel
- name: include update module
  include: update_epel/internet.yml
  when: result.stdotut == 'Connection'

- name: include epel for local
  include: update_epel/local.yml
  when: result.stdotut == 'Failed'


- name: include system_setup
  include: system_setup/main.yml


- name: include install_pip
  include: install_pip/internet.yml


- name: include trash-cli install
  include: alias_rm/main.yml