---
limit_conf:
  - { name: soft, info: "*   soft    nofile  65535" }
  - { name: hard, info: "*   hard    nofile  65535" }
DNS_Server:
  - { name: pubilc, info: "nameserver {{pubilc_adress}}"}
  - { name: Search_domain, info: "nameserver {{search_adress}}"}
