---
# defaults file for roles/redis
# Redis安装选项
Dependent:
  - gcc
  - gcc-c++
  - tcl
Redis_Version: "redis-{{version}}"
Download_Address: "http://download.redis.io/releases/{{Redis_Version}}.tar.gz"
Redis_Home: "{{Redis_Home}}"

# 配置文件位置
Redis_Config_Path: "{{Redis_Home}}/conf"
# 日中存放位置
logs_path: "{{Redis_Home}}/logs"
# Pid 存放位置
pid_path: "{{Redis_Home}}/redis.pid"
# 日志名称
logs_name: "{{Redis_Home}}/logs/redis.log"
# 配置文件使用---具体使用进行配置
port: 6379
# TCP接收队列长度，受/proc/sys/net/core/somaxconn和tcp_max_syn_backlog这两个内核参数的影响
tcpbacklog: 511
# 绑定的主机地址
bind: "{{ansible_eth0.ipv4.address}}"


