---
# defaults file for zookeeper-cluster
client_port: 2181
init_limit: 5
sync_limit: 2
tick_time: 2000

data_dir: /software/zookeeper/data
log_dir: /software/zookeeper/logs

zookeeper_home: /software/zookeeper-{{zookeeper_version}}/
zookeeper_config_path: /software/zookeeper-{{zookeeper_version}}/conf
INSTALL_HOME: /software
JAVA_HOME: /software/jdk1.7.0_79


profile:
  - { name: JAVA_HOME, info: "export JAVA_HOME=/software/jdk1.7.0_79"}
  - { name: PATH, info: "export PATH=${JAVA_HOME}/bin:$PATH"}