---
# vars file for tomcat
#外部传 java 版本,Tomcat 版本
INSTALL_HOME: /software
JAVA_NAME: jdk1.7.0_79
JAVA_HOME_7: /software/jdk1.7.0_79
# 更改 Tomcat 目录
TOMCAT_APP_PATH: "/software/tomcat_{{ project_name }}"
old_TOMCAT_PATH: /software/apache-tomcat-{{tomcat_version}}
# 配置文件调用
TOMCAT_SERVER_XML: "{{CATALINA_HOME}}/conf/"
TOMCAT_SERVER_JVM: "{{CATALINA_HOME}}/bin/"
TOMCAT_START_PORT: 8080
TOMCAT_DOCBASE: "/software/deploy_{{ project_name }}"
TOMCAT_CHECK_URL: "http://10.167.5.21:8080/index.html"