---
# solr 基础配置
script_path: "/software/script"
JAVA_HOME: /software/jdk1.7.0_79
solr_deploy_path: "/software/deploy_solrcloud/solrcloud/"
solr_version: "{{ verison }}"
solrcloud_config_path: "/software/solrcloud/config_files/"
solrcloud_libs_path: "/software/solrcloud/solrcloud_libs/"
solrcloud_home: "/software/solrcloud/solrcloud_home"
solrcloud_path:
  - "/software/solrcloud/config_files"
  - "/software/solrcloud/solrcloud_libs"
  - "/software/solrcloud/solrcloud_home"
tomcat_home: "/software/tomcat_solrcloud"
solr_libs_path: "{{ solr_deploy_path }}WEB-INF/lib/"

solrcloud_port: 8080
TOMCAT_START_PORT: 8080
JVM_OPTINOS: "$JAVA_OPTS -Xmx2048m -Xms2048m -Xmn1g -Xss1024k -DzkHost=10.167.5.23:2181,10.167.5.24:2181,10.167.5.25:2181 -Djava.security.egd=file:/dev/./urandom"