---
- name: Add mappings to /etc/security/limits.conf
  blockinfile:
    dest: /etc/security/limits.conf
    block: |
      {{item.info}}
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{item.name}}"
  with_items:
      - { name: soft, info: "*   soft    nofile  65536" }
      - { name: hard, info: "*   hard    nofile  65536" }
