---
# tasks file for nginx_log_cut


- name: Delete Old logs ---清空目录(1删除目录)
  file: path={{SAVE_LOGS_PATH}} state=absent


- name: Delete Old logs ---清空目录(2创建目录)
  file: path={{SAVE_LOGS_PATH}} state=directory

- name: transfer nginx_log_cut script to {{ansible_hostname}}
  template: src=nginx_log_cut.sh.j2 dest={{REMOTE_SCRIPT_PATH}}nginx_log_cut.sh mode=0755

  
- name: Create Crond For {{ansible_hostname}}
  cron:
    name="nginx_log_cut" minute="0" hour="0" job="{{REMOTE_SCRIPT_PATH}}nginx_log_cut.sh"


- name: Restart crond 
  shell: service crond restart
  tags: restart crond