---
- name: install supervisor use pip 
  pip:
    name: supervisor
    version: "{{ supervisor_version}}"


- name: check config dir for supervisor
  file:
    path: "{{ SUPERVISOR_CONF_BASE }}"
    state: directory
    mode: 0755


- name: transfer config to supervisor {{ SUPERVISOR_CONF_DIR }}
  template:
    src: supervisord.conf.j2
    dest: "{{ SUPERVISOR_CONF_BASE }}/supervisord.conf"
    mode: 0755


- name: setup supervisor include conf {{ SUPERVISOR_CONF_DIR }}
  file:
    path: "{{ SUPERVISOR_CONF_DIR }}"
    state: directory
    mode: 0755

- name: transfer start logstash_agent conf to supervisor  {{ SUPERVISOR_CONF_DIR }}
  template:
    src: supervisord_program.conf.j2
    dest: "{{ SUPERVISOR_CONF_DIR }}/{{ LOGSTASH_CONF_NAME }}"
    mode: 0755


- name: stup supervisor init script to {{ SUPERVISOR_CONF_BASE }}
  template:
    src: supervisord.sh.j2
    dest: "{{ SUPERVISOR_CONF_BASE }}/supervisord.sh"
    mode: 0755
