---
- name: update tomcat before transfer script for stop {{ project_name }}
  template:
    src: stop_process.sh.j2
    dest: "{{ SCRIPT_HOME }}stop_process.sh"
    mode: 0755

- name: run script stop {{ project_name }}
  shell: "./stop_process.sh"
  args:
    chdir: "{{ SCRIPT_HOME }}"
  register: return_status

- debug: msg="{{ project_name }} stop {{ return_status.stdout }} is sucessful!!! "
  when: return_status.stdout == "OK"


- name: remove old tomcat {{ project_name }}
  shell: mv {{ TOMCAT_APP_PATH }} tomcat_{{ project_name }}-old
  args:
    chdir: "{{ INSTALL_HOME }}"
  when: return_status.stdout == "OK"

- name: include install tomcat for {{ project_name }}
  include: install/main.yml


- name: start tomcat for {{ project_name }}
  shell: "nohup ./{{ project_name }}.py -d restart"
  args:
    chdir: "{{ SCRIPT_HOME }}"
