---
# tasks file for update_logstash
- name: Create patterns
  file: 
    dest={{patterns}}
    mode=0755
    state=directory
  when: remote_script_path.isdir is not defined
  tags: create patterns


- name: Copy nginx to remote
  copy:
    src=nginx dest="{{patterns}}/nginx" mode=0755
  tags: create patterns


- name: copy logstash_conf
  template:
    src=logstash-shipper.conf.j2
    dest={{logstash_conf_path}}logstash-shipper.conf
    mode=0644

- name: stop supervisor
  shell: /etc/init.d/supervisor stop
  args:
    chdir: /etc/init.d/
  tags: stop supervisor

- name: start supervisor
  shell: /etc/init.d/supervisor start
  args:
    chdir: /etc/init.d/
  tags: start supervisor