---
# 创建基础目录
- name: create install INSTALL_HOME
  file:
    dest: "{{ INSTALL_HOME }}"
    state: directory
    mode: 0755


# 进行判断 jdk 是否存在
- name: JAVA_HOME is exist?
  shell: "find {{ INSTALL_HOME }}  -name {{ JAVA_NAME }}  | wc -l"
  register: stdout_result
  ignore_errors: True


# 配置 JDK
- name: unarchive jdk to remote server
  unarchive:
    src: jdk-7u79-linux-x64.tar.gz
    dest: "{{ INSTALL_HOME }}"
  when: (stdout_result.stdout == "0")



- name: Install Tomcat 7
  unarchive:
    src: apache-tomcat-7.0.76.tar.gz
    dest: "{{INSTALL_HOME}}"


# 删除 webapps 下无用文件
- name: delete remote serer tomcat7 webapps/*
  shell: rm -rf *
  args:
    chdir: "{{INSTALL_HOME}}/apache-tomcat-7.0.76/webapps/"

# Create init process path
- name: Create tomcat process directory
  file:
    path: "{{TOMCAT_DOCBASE}}"
    state: directory

- name: Create index.html to process path
  template:
    src: index.html.j2
    dest: "{{TOMCAT_DOCBASE}}/index.html"
    mode: 0600

- name: Configure Tomcat 7
  template:
    src: server.xml.j2
    dest: "{{TOMCAT_SERVER_XML}}server.xml"
    mode: 0600

- name: Configure Tomcat catalina.sh
  template:
    src: catalina.sh.j2
    dest: "{{TOMCAT_SERVER_JVM}}catalina.sh"
    mode: 0755

- name: Configure tomcat.py
  template:
    src: tomcat.py.j2
    dest: "{{TOMCAT_SERVER_JVM}}process_tomcat.py"
    mode: 0755

- name: change tomcat dir name
  stat: path="{{ old_TOMCAT_PATH }}"
  register: old_path


- name: change tomcat process name
  command: "mv {{ old_TOMCAT_PATH }} {{ TOMCAT_APP_PATH }}"
  when: old_path.stat.exists