---
- name: install tomcat
  include: install/main.yml
  tags: install

- name: change tomcat config
  include: config/main.yml
  tags: setup_config


- name: update tomcat
  include: update/main.yml
  tags: update