---
USER: mysql
GROUP: mysql

# 安装依赖
packages:
  - numactl
  - perl
  - net-tools
  - autoconf 
  - libaio

# Mysql 配置文件
PORT: 3306
PASSWORD: 27GUv%y7
DATADIR: /data/databases/
LOGSDIR: /data/mysql_logs
LOGERRNAME: mysql.err
PIDSOCK: /data/run_info
# thread_concurrency应设为CPU核数的2倍
THREAD_CONCURRENCY: 4