---
USER: mysql
GROUP: mysql

# 安装依赖
packages:
  - numactl
  - perl
  - net-tools
  - autoconf 
  - libaio

# Mysql 配置文件
PORT: 3306
PASSWORD: 27GUv%y7
DATADIR: /software/databases/
LOGSDIR: /software/mysqllogs
LOGERRNAME: mysql.err
PIDSOCK: /software/runinfo
# thread_concurrency应设为CPU核数的2倍
THREAD_CONCURRENCY: 8