---
# vars file for mysql
# Mysql parameter List
## Mysql Verion
mysql_service: mysqld
mysql_version: 5.5.39
mysql_tar_name: mysql-{{mysql_version}}.tar.gz
## Mysql Files Tmp Save Path
Files_Tmp_Path: /tmp/packages/

## Install Mysql Library
Library:
  - gcc
  - gcc-c++
  - cmake
  - ncurses-devel
  - bison

## Mysql User and Group
mysql_user: mysql
mysql_group: mysql

## Mysql Install parameter
up_path: /software/
software_path: "{{up_path}}mysql-5"
mysql_data_path: "{{up_path}}mysql-data"
sock_path: "/tmp/mysqld.sock"
mysql_pid_path: "{{software_path}}/mysql.pid"
mysql_port: 3306
mysql_config: /etc/my.cnf
## Compile parameter
compile:  CFLAGS="-O3" CXX=gcc CXXFLAGS="-O3 -felide-constructors -fno-exceptions -fno-rtti" cmake -DMYSQL_USER={{mysql_user}} -DCMAKE_INSTALL_PREFIX={{software_path}} -DMYSQL_DATADIR={{mysql_data_path}} -DMYSQL_UNIX_ADDR={{sock_path}} -DEXTRA_CHARSETS=all -DDEFAULT_CHARSET=utf8 -DDEFAULT_COLLATION=utf8_general_ci -DWITH_INNOBASE_STORAGE_ENGINE=1 -DENABLED_LOCAL_INFILE=1 -DWITH_EMBEDDED_SERVER=1 -DSERVER-SUFFIX=EMTXDotCom -DWITH_DEBUG=0
